#!/bin/sh
cd "${0%/*}" || exit 1
. $WM_PROJECT_DIR/bin/tools/RunFunctions

echo "Copying 'initial' to 0"
rm -rf 0
cp -r initial 0

runApplication blockMesh
runApplication setFields
runApplication laserbeamFoam
