#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application="$(getApplication)"

cp -r initial 0
runApplication blockMesh 
runApplication setSolidFraction -subDivisions 4
runApplication transformPoints -rotate "((0 1 0) (0 0 1))" # this is needed in case of the ray tracing laser
sed -i '' 's/value[[:space:]]*( 0 0 -9\.81);/value           ( 0 9.81 0);/' constant/g
runApplication laserMeltFoam
#------------------------------------------------------------------------------
