#!/bin/bash
cd ${0%/*} || exit 1    # run from this directory

targetType=""

# Parse arguments for library compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

(cd geometricVoF && ./Allwmake $targetType $* 2>&1 | tee log.Allwmake)
(cd laserHeatSource && ./Allwmake $targetType $* 2>&1 | tee log.Allwmake)
(cd MTHD && ./Allwmake $targetType $* 2>&1 | tee log.Allwmake)
(cd functionObjects && ./Allwmake $targetType $* 2>&1 | tee log.Allwmake)
(cd transportModels/incompressible && ./Allwmake $targetType $* 2>&1 | tee log.Allwmake)
(cd turbulenceModel && ./Allwmake $targetType $* 2>&1 | tee log.Allwmake)
