#!/usr/bin/env python3
"""Emit constant/transportProperties for Al-5%Mg, in laserbeamFoam's own format.

Structure taken from the Plate2D tutorial on OpenFoam_com_main (which is a STEEL
case: rho 8000, Tsolidus 1658). Every key below is one laserbeamFoam actually
reads; the values are the Phase 2 property set.

Polynomials are fitted here, not typed, so the dictionary and the property
tables can never drift apart.
"""
import numpy as np, importlib.util

spec = importlib.util.spec_from_file_location("mp", "/home/claude/make_props.py")
mp = importlib.util.module_from_spec(spec); spec.loader.exec_module(mp)

T = np.linspace(300, 2000, 600)
k = np.array([mp.k_th(t) for t in T])
cp = np.array([mp.cp(t) for t in T])

# kappa: weight the SOLID branch 20x. Justification in the header comment below.
ck = np.polyfit(T, k, 7, w=np.where(T <= 815, 20.0, 1.0))[::-1]
ccp = np.polyfit(T, cp, 5)[::-1]
fmt = lambda c, n: " ".join(f"{c[i]:.6e}" if i < len(c) else "0" for i in range(n))

# argon, 300 K 1 atm
k_ar = lambda t: 0.0084 + 3.10e-5 * t          # W/mK, ~0.018 at 300 K to 0.070 at 2000 K

DOC = f"""/*--------------------------------*- C++ -*----------------------------------*\\
| transportProperties -- Al-5%Mg (5A05 / ER5356) for laserbeamFoam, ESI v2506  |
| Generated by make_transport.py. Do not hand-edit: regenerate.                |
|                                                                             |
| Key names and structure copied from tutorials/laserbeamFoam/Plate2D, which   |
| is a STEEL case. Values are the Phase 2 property set for Al-5%Mg.            |
|                                                                             |
| TWO STRUCTURAL LIMITATIONS FOUND WHILE WRITING THIS -- read before using.    |
|                                                                             |
| 1. Elec_conductivity is a SINGLE SCALAR per phase. It cannot be made         |
|    temperature dependent through this dictionary. The Phase 2 sigma_e(T)     |
|    runs 1.64e7 (300 K) -> 8.15e6 (solidus) -> 3.65e6 (liquidus), a factor    |
|    of 4.5 across the range, and all of that collapses to one number here.    |
|    3.65e6, the liquidus value, is used because the melt is what carries the  |
|    MHD. But note the SOLID is then understated by 4.5x -- which matters for  |
|    Phase 6, where injected current must flow through the substrate. Expect   |
|    to need a code change there, not a dictionary entry.                      |
|                                                                             |
| 2. poly_kappa was ONE polynomial per phase, and aluminium's thermal          |
|    conductivity HALVES on melting (162 -> 81 W/mK across 91 K). No smooth    |
|    degree-7 polynomial can represent that step -- the best full-range fit    |
|    was 84% wrong at the liquidus, sitting exactly at the solidification      |
|    front where Darcy damping kills velocity and conduction dominates.        |
|    RESOLVED by patch_kappa.py, which adds poly_kappa_solid and               |
|    poly_kappa_liquid and blends them by liquid fraction in updateKappaCp.H,  |
|    following the pattern the solver already uses for emS/emL in TEqn.H.      |
|    Worst error anywhere is now 2.6%, confined to the mushy window, and that  |
|    residual is a difference of mixing rule rather than a fitting failure.    |
|    THIS DICTIONARY REQUIRES THE PATCHED SOLVER to get that accuracy. On an   |
|    unpatched build the poly_kappa fallback below is used instead, silently,  |
|    and the 84% error returns. Check the "Metal kappa:" line the solver       |
|    prints at startup.                                                        |
\\*---------------------------------------------------------------------------*/
FoamFile
{{
    version     2.0;
    format      ascii;
    class       dictionary;
    location    "constant";
    object      transportProperties;
}}
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

interfaceTrackingScheme isoAdvector;

electromagnetics    true;      // MTHD on. Costs 2.7x wall clock (Phase 1).

phases (metal gas);

metal
{{
    transportModel  Newtonian;

    // kinematic viscosity = mu/rho = 1.25e-3/2650. [MEAS] Assael et al. 2006
    // for liquid Al, 1.25 mPa.s at the melting point.
    nu              {1.25e-3/2650:.5e};

    // [ZHAO] Table 4. ONE constant for both phases; real liquid Al-5Mg near the
    // liquidus is ~2350, so the melt is modelled ~13% heavy. Kept for fidelity.
    rho             2650;

    Tsolidus        815;        // K  [ZHAO] Table 4, via Mills LM5/5182
    Tliquidus       906;        // K  [ZHAO] Table 4, via Mills LM5/5182
    LatentHeat      3.58e5;     // J/kg [ZHAO] Table 4
    beta            3.0e-5;     // 1/K  [ZHAO] Table 4

    // [CONSTR] Wiedemann-Franz from sigma_e(T), validated to 1-2% against pure
    // Al solid and liquid at Tm and against 5182 at 300 K.
    //
    // TWO BRANCHES. Aluminium's kappa halves on melting, which one polynomial
    // cannot represent (84% wrong at the liquidus). These are blended by
    // liquid fraction in updateKappaCp.H -- see patch_kappa.py. Worst error
    // anywhere with the blend: 2.6%, confined to the mushy window.
    poly_kappa_solid    (1.549249e+01 5.364784e-01 -7.678846e-04 5.249716e-07 -1.466608e-10 0 0 0);
    poly_kappa_liquid   (1.913178e+01 1.058187e-01 -5.717666e-05 1.927299e-08 -2.557323e-12 0 0 0);

    // Fallback for an UNPATCHED solver. Ignored when the two entries above are
    // present. Kept so this dictionary stays usable either way.
    poly_kappa      ({fmt(ck, 8)});

    // [CONSTR] anchored on pure Al; Neumann-Kopp for 5% Mg shifts it +0.7%.
    // Max fit error 1.6% over 300-2000 K.
    poly_cp         ({fmt(ccp, 8)});

    // [CONSTR] liquidus value. See limitation 1 -- this is not a constant in
    // reality, and the solid is 4.5x higher.
    Elec_conductivity   3.65e6;
    Mag_permitivity     1.25664e-6;   // [ZHAO] 4 pi e-7, non-magnetic alloy
}}

gas
{{
    transportModel  Newtonian;

    // argon at 300 K, 1 atm: mu 2.23e-5 Pa.s, rho 1.6228 kg/m3
    nu              {2.23e-5/1.6228:.5e};
    rho             1.6228;

    // dummy phase-change values so the gas is always treated as liquid
    Tsolidus        1.0;
    Tliquidus       10.0;
    LatentHeat      1;

    // ideal gas, beta = 1/T at 300 K. If the gas phase shows spurious buoyant
    // motion, reduce this -- the tutorial used 4e-5 for the same reason.
    beta            3.33e-3;

    // argon conductivity, linear fit 0.018 (300 K) to 0.070 (2000 K)
    poly_kappa      ({k_ar(0):.6e} {3.10e-5:.6e} 0 0 0 0 0 0);

    // monatomic ideal gas, cp = 5R/2M = 520.3 J/kgK, constant
    poly_cp         (520.3 0 0 0 0 0 0 0);

    // [MEAS-ish] the tutorial's own floor, ratio 1e-6 to the metal. Held
    // div(muH) at 1e-12 across the jump in Gate B. Do not lower without
    // re-checking divergence.
    Elec_conductivity   3.65;
    Mag_permitivity     1.25664e-6;
}}

// ============================================================ interface
// [ZHAO]/[EST] Both are sourced to Mills' PURE ALUMINIUM chapter (ref [34]),
// not the LM5/5182 alloy chapter used for every thermal property. Mg is
// strongly surface-active in Al, so a true Al-5Mg value is lower. 0.85 happens
// to match the OXIDIZED pure-Al figure (0.865); clean pure Al is 1.10.
// Marangoni drives the paper's headline result, so this is the single largest
// uncertainty in the replication. SENSITIVITY CASE REQUIRED.
sigma               0.85;       // N/m
Marangoni_Constant  -1.55e-4;   // N/m/K

p0                  101300;     // Pa [ZHAO] Table 4

// Vaporisation. Zhao assumption 3 explicitly NEGLECTS vaporisation heat and
// mass loss. Real Al values are given so the model is physical if it ever
// triggers, but at WAAM pool temperatures it should not.
Tvap                2743;       // K    [MEAS] boiling point of aluminium
Mm                  0.02698;    // kg/mol [MEAS] molar mass of aluminium
LatentHeatVap       1.05e7;     // J/kg [MEAS] Al heat of vaporisation

// EMISSIVITY, blended by liquid fraction in TEqn.H line 15:
//     em = epsilon1*emL + (1 - epsilon1)*emS
// Confirmed by reading the source. The tutorial's 0.4/0.1 are STEEL values.
// [EST] oxidised aluminium: solid 0.3, liquid 0.15. Zhao gives no emissivity.
// Not negligible: radiation overtakes convection at ~1300 K and is 2x it by
// 2000 K, and this pool sits above 906 K throughout. Sensitivity case worthwhile.
emS                 0.3;
emL                 0.15;

TRef                TRef [0 0 0 1 0 0 0] 300;

// ************************************************************************* //
"""

open("transportProperties", "w").write(DOC)
print(DOC)
